// Builds src/basemap.js: an offline world map (land + country borders) that
// Quackdex draws under the tile layer, so the map still reads as a map when
// tiles can't load (offline, or inside a sandbox that blocks tile servers).
//
//   npm install        (in duck-app/, for world-atlas + topojson-client)
//   node tools/make-basemap.mjs
//
// Coordinates are quantised to 0.01° and delta-encoded into strings of
// comma-separated integers, which roughly halves the size of plain GeoJSON.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as topojson from "topojson-client";

const here = path.dirname(fileURLToPath(import.meta.url));
const atlas = (name) =>
  JSON.parse(fs.readFileSync(path.join(here, "..", "node_modules", "world-atlas", name), "utf8"));

function encodeLine(coords) {
  let px = 0, py = 0;
  const out = [];
  for (const [x, y] of coords) {
    const qx = Math.round(x * 100), qy = Math.round(y * 100);
    if (out.length && qx === px && qy === py) continue;
    out.push(qx - px, qy - py);
    px = qx; py = qy;
  }
  return out.join(",");
}

const land = atlas("land-50m.json");
const landGeo = topojson.feature(land, land.objects.land);
const polygons = landGeo.features.flatMap((f) =>
  f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates,
);
const landRings = polygons.map((poly) => poly.map(encodeLine));

const countries = atlas("countries-50m.json");
const borders = topojson.mesh(countries, countries.objects.countries, (a, b) => a !== b);
const borderLines = borders.coordinates.map(encodeLine);

const src =
  "// Generated by tools/make-basemap.mjs from world-atlas (Natural Earth, public domain). Do not edit.\n" +
  `export const LAND = ${JSON.stringify(landRings)};\n` +
  `export const BORDERS = ${JSON.stringify(borderLines)};\n`;

const outPath = path.join(here, "..", "src", "basemap.js");
fs.writeFileSync(outPath, src);
console.log(`wrote ${path.relative(process.cwd(), outPath)}: ${(src.length / 1024).toFixed(0)} KB, ` +
  `${landRings.length} land polygons, ${borderLines.length} border lines`);
