// The Quackdex species directory.
//
// Every living duck species (plus a few recently extinct ones and the common
// domestic breeds you meet at park ponds), grouped by how they live. Taxonomy
// follows current IOC/AOS usage; IUCN statuses are the most recent
// assessment at the time of writing. This is prototype data: verify before
// relying on it.
//
// Fields
//   id       stable slug, also what the photo identifier answers with
//   name     common name
//   sci      scientific name
//   group    key into GROUPS
//   status   IUCN Red List: LC NT VU EN CR EX, or DOM for domestic breeds
//   len      body length in cm
//   regions  space-separated keys into REGIONS
//   habitat  where to look
//   marks    how to recognise it (adult male unless stated)
//   about    one thing worth knowing
//   colors   [head, bill, breast, body] used to tint the directory duck
//   x        optional extra detail for commonly seen species

export const REGIONS = {
  NA: "North & Central America",
  SA: "South America",
  EU: "Europe",
  AF: "Africa",
  AS: "Asia",
  OC: "Australia & Pacific",
  AN: "Sub-Antarctic islands",
};

export const GROUPS = {
  dabbling: {
    name: "Dabbling ducks",
    blurb: "Surface feeders that tip bottoms-up instead of diving, and spring straight up out of the water to fly.",
    diet: "Seeds, aquatic plants, snails and insects taken at or just below the surface.",
    color: "#2E8B57",
  },
  diving: {
    name: "Diving ducks",
    blurb: "Pochards and scaup: compact ducks with legs set far back that dive for their food and patter across the water to take off.",
    diet: "Roots and tubers of water plants, clams, snails and insect larvae from the bottom.",
    color: "#8B4A2B",
  },
  sea: {
    name: "Sea ducks",
    blurb: "Eiders, scoters, goldeneyes and kin: tough divers of cold coasts and northern lakes.",
    diet: "Mussels, clams, crabs and other shellfish, swallowed whole and crushed in the gizzard.",
    color: "#3C5A74",
  },
  merganser: {
    name: "Mergansers",
    blurb: "Slim diving ducks with serrated, saw-edged bills built for gripping fish.",
    diet: "Mostly small fish, plus crayfish and aquatic insects.",
    color: "#7A2E3A",
  },
  perching: {
    name: "Perching ducks",
    blurb: "Tree-nesting ducks with sharp claws for gripping branches; many are strikingly colourful.",
    diet: "Seeds, acorns, fruit, plants and insects.",
    color: "#B5651D",
  },
  whistling: {
    name: "Whistling ducks",
    blurb: "Long-legged, upright ducks that call with clear whistles and often feed at night.",
    diet: "Seeds, grain and water plants, often foraged at night.",
    color: "#A0522D",
  },
  stifftail: {
    name: "Stiff-tailed ducks",
    blurb: "Chunky divers with spiky tails they cock upright; males of many species have bright blue bills.",
    diet: "Midge larvae, other aquatic invertebrates and seeds sieved from the bottom.",
    color: "#2F6FA8",
  },
  shelduck: {
    name: "Shelducks & specialists",
    blurb: "Goose-like shelducks, steamer ducks, torrent ducks and other one-of-a-kind lineages.",
    diet: "Varies widely: grazing, sifting mud for invertebrates, or hunting larvae in rapids.",
    color: "#5E6C3A",
  },
  domestic: {
    name: "Domestic breeds",
    blurb: "Farm and park ducks bred from Mallards (or Muscovies). Very common on town ponds, often hybridising with wild birds.",
    diet: "Omnivorous: grass, insects, snails, and whatever people feed them (skip the bread; try peas or oats).",
    color: "#6C7A89",
  },
};

export const STATUS = {
  LC: { label: "Least Concern", short: "LC" },
  NT: { label: "Near Threatened", short: "NT" },
  VU: { label: "Vulnerable", short: "VU" },
  EN: { label: "Endangered", short: "EN" },
  CR: { label: "Critically Endangered", short: "CR" },
  EX: { label: "Extinct", short: "EX" },
  DOM: { label: "Domestic breed", short: "DOM" },
};

export const SPECIES = [
  // ── Dabbling ducks ────────────────────────────────────────────────
  {
    id: "mallard", name: "Mallard", sci: "Anas platyrhynchos", group: "dabbling", status: "LC", len: "50–65",
    regions: "NA EU AS AF OC", habitat: "Almost any fresh water: park ponds, rivers, marshes, city canals.",
    marks: "Glossy green head, thin white neck ring, chestnut breast, grey body and a curled black tail feather. Females are mottled brown with an orange-and-black bill. Both show a blue wing patch edged in white.",
    about: "The ancestor of nearly every domestic duck breed, and the only duck whose females give the classic loud 'quack'.",
    colors: ["1F7A4D", "F2C230", "7B3F24", "C9CED3"],
    x: {
      weight: "0.7–1.6 kg", wingspan: "81–98 cm", lifespan: "5–10 years in the wild (record 29)",
      voice: "Females give the familiar descending 'QUACK quack quack'; males a soft, raspy 'rhaeb'.",
      facts: [
        "Drakes moult into a dull 'eclipse' plumage each summer and look like females for a few weeks.",
        "Mallards can sleep with one eye open, keeping half the brain alert for predators.",
        "They hybridise freely, so park ponds are full of 'manky mallards' with odd patches of white.",
      ],
    },
  },
  {
    id: "american-black-duck", name: "American Black Duck", sci: "Anas rubripes", group: "dabbling", status: "LC", len: "54–59",
    regions: "NA", habitat: "Salt marshes, beaver ponds and wooded wetlands of eastern North America.",
    marks: "Dark chocolate-brown body contrasting with a paler grey-brown face; olive-yellow bill; violet-blue wing patch without the Mallard's white borders. Flashes white underwings in flight.",
    about: "Hardier and warier than Mallards, it thrives in cold coastal marshes through the winter.",
    colors: ["8C7A62", "B8B04A", "3E2E22", "3E2E22"],
    x: {
      weight: "0.7–1.6 kg", wingspan: "88–95 cm", lifespan: "Record 26 years",
      voice: "Quacks almost identical to a Mallard's.",
      facts: [
        "Heavy hybridisation with Mallards is one of the main threats to its genetic identity.",
        "It is one of the most sought-after ducks by hunters in the Atlantic Flyway, which drove decades of monitoring.",
      ],
    },
  },
  {
    id: "mottled-duck", name: "Mottled Duck", sci: "Anas fulvigula", group: "dabbling", status: "LC", len: "44–61",
    regions: "NA", habitat: "Coastal marshes of Florida and the Gulf of Mexico.",
    marks: "Warm brown, mottled body with an unstreaked buffy face and bright yellow bill; a black spot at the corner of the gape.",
    about: "One of the few dabbling ducks that stays in the southern USA all year instead of migrating.",
    colors: ["B39B77", "E8C23A", "7B5B3C", "7B5B3C"],
  },
  {
    id: "mexican-duck", name: "Mexican Duck", sci: "Anas diazi", group: "dabbling", status: "LC", len: "51–56",
    regions: "NA", habitat: "Highland marshes and rivers from the southwestern USA to central Mexico.",
    marks: "Looks like a female Mallard in both sexes, but darker bodied with a plain tail and a greenish-yellow bill in males.",
    about: "Recognised as a full species again in 2020 after being lumped with the Mallard for decades.",
    colors: ["9C8468", "B7BE4A", "6E5438", "6E5438"],
  },
  {
    id: "hawaiian-duck", name: "Hawaiian Duck (Koloa)", sci: "Anas wyvilliana", group: "dabbling", status: "EN", len: "44–50",
    regions: "OC", habitat: "Streams, taro fields and wetlands on the Hawaiian Islands.",
    marks: "A small, mottled brown duck like a female Mallard; males may show hints of a greenish head.",
    about: "Hybridisation with feral Mallards is its biggest threat today.",
    colors: ["6B6A4F", "8A8A40", "6E4E36", "7A6048"],
  },
  {
    id: "laysan-duck", name: "Laysan Duck", sci: "Anas laysanensis", group: "dabbling", status: "CR", len: "38–43",
    regions: "OC", habitat: "Laysan Island and Midway Atoll in the northwest Hawaiian Islands.",
    marks: "Small, dark rufous-brown duck with a white eye ring of variable size.",
    about: "Once down to perhaps a dozen birds, it hunts brine flies by running through swarms with its bill open.",
    colors: ["5B4632", "4F5B3A", "5B4632", "6A5240"],
  },
  {
    id: "pacific-black-duck", name: "Pacific Black Duck", sci: "Anas superciliosa", group: "dabbling", status: "LC", len: "50–60",
    regions: "OC AS", habitat: "Any wetland across Australia, New Zealand and the southwest Pacific.",
    marks: "Dark brown body with a striking face: pale cream with two black stripes through the eye and cheek. Green wing patch.",
    about: "Australia's most familiar duck, found everywhere from outback dams to city lakes.",
    colors: ["D9C9A6", "4A5560", "4A3A2C", "4A3A2C"],
  },
  {
    id: "philippine-duck", name: "Philippine Duck", sci: "Anas luzonica", group: "dabbling", status: "VU", len: "48–58",
    regions: "AS", habitat: "Freshwater marshes, lakes and rice fields in the Philippines.",
    marks: "Cinnamon-orange head and neck with a black crown and eye-stripe, contrasting with a grey-brown body.",
    about: "Found only in the Philippines, where hunting and wetland loss have cut its numbers.",
    colors: ["D98B4A", "5C6B78", "6F6358", "6F6358"],
  },
  {
    id: "indian-spot-billed-duck", name: "Indian Spot-billed Duck", sci: "Anas poecilorhyncha", group: "dabbling", status: "LC", len: "55–63",
    regions: "AS", habitat: "Lakes, marshes and rice paddies of the Indian subcontinent.",
    marks: "Scaly grey-brown body, pale head with a dark crown and eye-line, black bill with a bright yellow tip and red spots at the base.",
    about: "The red spots at the base of the bill are its giveaway.",
    colors: ["CFC3AE", "2A2A2A", "7C6B58", "8A7A66"],
  },
  {
    id: "eastern-spot-billed-duck", name: "Eastern Spot-billed Duck", sci: "Anas zonorhyncha", group: "dabbling", status: "LC", len: "55–63",
    regions: "AS", habitat: "Wetlands, rivers and city ponds in East Asia.",
    marks: "Like the Indian species but darker and browner, with a dark cheek stripe and no red bill spots.",
    about: "A common city-park duck in Japan, Korea and eastern China.",
    colors: ["C7B89C", "2A2A2A", "6B5A48", "6B5A48"],
  },
  {
    id: "yellow-billed-duck", name: "Yellow-billed Duck", sci: "Anas undulata", group: "dabbling", status: "LC", len: "51–63",
    regions: "AF", habitat: "Lakes, dams and rivers in eastern and southern Africa.",
    marks: "Grey-brown scalloped plumage with a bright yellow bill that has a black saddle.",
    about: "Southern Africa's commonest duck, it hybridises readily with released Mallards.",
    colors: ["6F6558", "F2C230", "766A5C", "7A6E60"],
  },
  {
    id: "african-black-duck", name: "African Black Duck", sci: "Anas sparsa", group: "dabbling", status: "LC", len: "48–57",
    regions: "AF", habitat: "Fast, rocky streams and rivers in sub-Saharan Africa.",
    marks: "Blackish duck with bold white spots on the back and orange legs.",
    about: "A river specialist that defends its own stretch of stream year-round.",
    colors: ["2B2B2E", "4A4F5A", "2B2B2E", "34343A"],
  },
  {
    id: "mellers-duck", name: "Meller's Duck", sci: "Anas melleri", group: "dabbling", status: "EN", len: "55–68",
    regions: "AF", habitat: "Rivers, lakes and marshes in the highlands of eastern Madagascar.",
    marks: "Large, dark, scaly brown duck with a plain face and green wing patch.",
    about: "Found only on Madagascar, where wetland loss and hunting have made it rare.",
    colors: ["5F5143", "7C8A7A", "5B4A3A", "5B4A3A"],
  },
  {
    id: "northern-pintail", name: "Northern Pintail", sci: "Anas acuta", group: "dabbling", status: "LC", len: "51–76",
    regions: "NA EU AS AF", habitat: "Open marshes, flooded fields and prairie ponds; winters on coasts and farmland.",
    marks: "Elegant and long-necked: chocolate head, white stripe running up the neck, grey body and a long needle-pointed tail.",
    about: "One of the most widespread ducks on Earth, breeding across the whole northern hemisphere.",
    colors: ["5A3D2B", "5E6B78", "F4F4F2", "B5B9BD"],
    x: {
      weight: "0.5–1.4 kg", wingspan: "80–95 cm", lifespan: "Record 27 years",
      voice: "Males give a soft, fluty whistle, 'prrip-prrip'.",
      facts: [
        "Pintails are among the fastest ducks, reaching around 80 km/h in level flight.",
        "They nest farther from water than most ducks, sometimes more than a kilometre away.",
      ],
    },
  },
  {
    id: "white-cheeked-pintail", name: "White-cheeked Pintail", sci: "Anas bahamensis", group: "dabbling", status: "LC", len: "38–50",
    regions: "NA SA", habitat: "Mangroves, lagoons and brackish ponds of the Caribbean and South America.",
    marks: "Bright white cheeks and throat, brown spotted body, and a blue-grey bill with a red base.",
    about: "Also called the Bahama Pintail; both sexes look alike.",
    colors: ["F5F2EA", "C83A3A", "B08A62", "A98563"],
  },
  {
    id: "yellow-billed-pintail", name: "Yellow-billed Pintail", sci: "Anas georgica", group: "dabbling", status: "LC", len: "43–65",
    regions: "SA AN", habitat: "Lakes and marshes across South America, including South Georgia.",
    marks: "Plain brown duck with a pointed tail and a bright yellow bill.",
    about: "The South Georgia race is a rare carnivorous duck that scavenges seal carcasses.",
    colors: ["9C8466", "F2C230", "8C7254", "8C7254"],
  },
  {
    id: "eatons-pintail", name: "Eaton's Pintail", sci: "Anas eatoni", group: "dabbling", status: "VU", len: "35–45",
    regions: "AN", habitat: "Streams and pools on the Kerguelen and Crozet Islands.",
    marks: "A small, dark brown pintail; males only briefly show a hint of the white neck stripe.",
    about: "Lives on remote sub-Antarctic islands where introduced cats are its main threat.",
    colors: ["6A5442", "4F5A66", "6A5442", "6A5442"],
  },
  {
    id: "green-winged-teal", name: "Green-winged Teal", sci: "Anas carolinensis", group: "dabbling", status: "LC", len: "31–39",
    regions: "NA", habitat: "Shallow marshes, mudflats and flooded fields.",
    marks: "Tiny. Chestnut head with a glossy green band behind the eye, grey body, and a vertical white stripe on the side of the breast.",
    about: "North America's smallest dabbling duck, flying in fast, twisting flocks like shorebirds.",
    colors: ["8B3A24", "2A2A2A", "D8C8A8", "A9AFB5"],
    x: {
      weight: "0.2–0.5 kg", wingspan: "52–59 cm", lifespan: "Record 20 years",
      voice: "Males give a clear, cricket-like 'preep'.",
      facts: [
        "In winter they sift mudflats for tiny seeds that larger ducks can't use.",
        "It was split from the Eurasian Teal because the males differ in the white stripe: vertical here, horizontal there.",
      ],
    },
  },
  {
    id: "eurasian-teal", name: "Eurasian Teal", sci: "Anas crecca", group: "dabbling", status: "LC", len: "34–43",
    regions: "EU AS AF", habitat: "Marshes, pools and estuaries across Europe and Asia.",
    marks: "Chestnut head with a green eye patch edged in cream, grey body with a long horizontal white stripe, and a yellow triangle under the tail.",
    about: "Europe's smallest duck, also called the Common Teal.",
    colors: ["8B3A24", "2A2A2A", "D8C8A8", "A9AFB5"],
  },
  {
    id: "andean-teal", name: "Andean Teal", sci: "Anas andium", group: "dabbling", status: "LC", len: "38–43",
    regions: "SA", habitat: "High Andean lakes and bogs above 3,000 m.",
    marks: "Small, greyish, spotted duck with a dark grey bill and a greenish wing patch.",
    about: "Lives at altitudes where few other ducks can breed.",
    colors: ["8B8578", "4A5058", "7A7064", "7A7064"],
  },
  {
    id: "yellow-billed-teal", name: "Yellow-billed Teal", sci: "Anas flavirostris", group: "dabbling", status: "LC", len: "35–45",
    regions: "SA", habitat: "Ponds, lakes and marshes of southern South America.",
    marks: "Small, grey-brown speckled duck with a bright yellow bill.",
    about: "Often nests in the stick nests of Monk Parakeets.",
    colors: ["9A8F80", "F2C230", "8A7E6E", "8A7E6E"],
  },
  {
    id: "cape-teal", name: "Cape Teal", sci: "Anas capensis", group: "dabbling", status: "LC", len: "44–48",
    regions: "AF", habitat: "Saline lakes, pans and sewage ponds in Africa.",
    marks: "Pale grey, finely speckled duck with a bright pink bill.",
    about: "Happily uses salty and alkaline lakes that most ducks avoid.",
    colors: ["CFCBC4", "E88A9A", "BDB6AC", "B3ACA2"],
  },
  {
    id: "red-billed-teal", name: "Red-billed Teal", sci: "Anas erythrorhyncha", group: "dabbling", status: "LC", len: "43–48",
    regions: "AF", habitat: "Shallow freshwater wetlands of southern and eastern Africa.",
    marks: "Dark brown cap over pale cheeks, scaly brown body and a red bill.",
    about: "One of the most abundant ducks in southern Africa, moving nomadically after rains.",
    colors: ["EDE3D0", "D9443C", "7F6A52", "7F6A52"],
  },
  {
    id: "berniers-teal", name: "Bernier's Teal", sci: "Anas bernieri", group: "dabbling", status: "EN", len: "40",
    regions: "AF", habitat: "Brackish lakes and mangroves of western Madagascar.",
    marks: "Small warm-brown teal with a red-pink bill and a white-bordered black wing patch.",
    about: "Also called the Madagascar Teal; only a few thousand remain.",
    colors: ["A57E58", "D67A7A", "9C7654", "9C7654"],
  },
  {
    id: "sunda-teal", name: "Sunda Teal", sci: "Anas gibberifrons", group: "dabbling", status: "NT", len: "37–47",
    regions: "AS", habitat: "Wetlands, lagoons and mangroves in Indonesia.",
    marks: "Grey-brown teal with a bulging forehead and red eyes.",
    about: "Its oddly domed forehead sets it apart from the Grey Teal of Australia.",
    colors: ["8C7B68", "3A3E44", "7B6A58", "7B6A58"],
  },
  {
    id: "grey-teal", name: "Grey Teal", sci: "Anas gracilis", group: "dabbling", status: "LC", len: "37–48",
    regions: "OC", habitat: "Any wetland in Australia and New Zealand, especially after floods.",
    marks: "Plain grey-brown teal with a pale throat, red eyes and a white-bordered green wing patch.",
    about: "A true nomad: it can breed within weeks of rain filling a dry lake.",
    colors: ["A89C8C", "3A3E44", "8A7C6C", "8A7C6C"],
  },
  {
    id: "chestnut-teal", name: "Chestnut Teal", sci: "Anas castanea", group: "dabbling", status: "LC", len: "38–48",
    regions: "OC", habitat: "Coastal estuaries and lagoons of southern Australia.",
    marks: "Glossy green head, rich chestnut body with a white patch near the tail, red eyes.",
    about: "Looks a little like a mini Mallard with a chestnut body.",
    colors: ["1E6B45", "3A3E44", "8C4A2A", "8C4A2A"],
  },
  {
    id: "andaman-teal", name: "Andaman Teal", sci: "Anas albogularis", group: "dabbling", status: "VU", len: "37–47",
    regions: "AS", habitat: "Mangroves, creeks and paddies of the Andaman Islands.",
    marks: "Dark brown teal with a variable white face patch and eye ring.",
    about: "Found only on the Andaman Islands in the Bay of Bengal.",
    colors: ["E8E2D6", "3A3E44", "5A4838", "5A4838"],
  },
  {
    id: "brown-teal", name: "Brown Teal (Pāteke)", sci: "Anas chlorotis", group: "dabbling", status: "NT", len: "36–46",
    regions: "OC", habitat: "Coastal streams and swamps of New Zealand.",
    marks: "Dark brown teal with a white eye ring; males have a greenish sheen on the head in breeding season.",
    about: "Mostly active at dusk and night, which helps it avoid predators.",
    colors: ["3F4A3A", "3A3E44", "6A4A32", "5A4634"],
  },
  {
    id: "auckland-teal", name: "Auckland Teal", sci: "Anas aucklandica", group: "dabbling", status: "NT", len: "36",
    regions: "OC", habitat: "Kelp-lined coasts and peat streams of the Auckland Islands.",
    marks: "Tiny, dark brown teal with a white eye ring and stubby wings.",
    about: "Flightless: with no ground predators on its islands, it gave up flying.",
    colors: ["4A3E30", "3A3E44", "5A4634", "5A4634"],
  },
  {
    id: "campbell-teal", name: "Campbell Teal", sci: "Anas nesiotis", group: "dabbling", status: "VU", len: "36",
    regions: "OC", habitat: "Tussock grassland and coasts of Campbell Island, New Zealand.",
    marks: "Tiny, very dark brown flightless teal with a narrow eye ring.",
    about: "Once thought extinct, it was rediscovered on a rat-free islet in 1975.",
    colors: ["3F352A", "3A3E44", "4C3E30", "4C3E30"],
  },
  {
    id: "gadwall", name: "Gadwall", sci: "Mareca strepera", group: "dabbling", status: "LC", len: "46–56",
    regions: "NA EU AS AF", habitat: "Marshes, lakes and park ponds with plenty of water plants.",
    marks: "Understated: finely patterned grey-brown body, black rear end, and a small white square on the wing. Females look like Mallards with an orange-sided bill.",
    about: "Gadwalls often steal plants brought to the surface by diving coots.",
    colors: ["9E958A", "3A3E44", "8C8074", "9A948C"],
    x: {
      weight: "0.5–1.3 kg", wingspan: "84–95 cm", lifespan: "Record 19 years",
      voice: "Males give a short, burping 'reb'; females a Mallard-like quack.",
      facts: [
        "The white wing patch is the easiest way to pick one out from a flock of Mallards.",
        "Gadwalls eat more leaves and stems than most dabblers, which lets them use deeper water.",
      ],
    },
  },
  {
    id: "falcated-duck", name: "Falcated Duck", sci: "Mareca falcata", group: "dabbling", status: "NT", len: "46–54",
    regions: "AS", habitat: "Lakes and rivers of eastern Siberia, China and Japan.",
    marks: "Bronze-green maned head that looks like a helmet, scaly grey body and long curved sickle-shaped tertial feathers.",
    about: "'Falcated' means sickle-shaped, after the drooping wing feathers.",
    colors: ["2F6B5A", "2A2A2A", "C0BCB4", "A7A9AB"],
  },
  {
    id: "eurasian-wigeon", name: "Eurasian Wigeon", sci: "Mareca penelope", group: "dabbling", status: "LC", len: "42–52",
    regions: "EU AS AF", habitat: "Estuaries, coastal grazing marsh and lakes; grazes on grass like a goose.",
    marks: "Chestnut head with a creamy-yellow forehead stripe, pink breast, grey body, short blue-grey bill with a black tip.",
    about: "Winter flocks fill estuaries with the males' whistled 'wheeoo'.",
    colors: ["A0442A", "8A9AAE", "C9A6A0", "B6B8BA"],
    x: {
      weight: "0.5–1.1 kg", wingspan: "71–80 cm", lifespan: "Record 34 years",
      voice: "A far-carrying whistled 'wheee-ooo' from males.",
      facts: [
        "It grazes on land far more than most ducks, trimming grass and eelgrass with its short bill.",
        "A few turn up each winter in North America among flocks of American Wigeon.",
      ],
    },
  },
  {
    id: "american-wigeon", name: "American Wigeon", sci: "Mareca americana", group: "dabbling", status: "LC", len: "42–59",
    regions: "NA", habitat: "Marshes, lakes, and parks and golf courses where it grazes on lawns.",
    marks: "White crown stripe (nicknamed 'baldpate'), broad green stripe behind the eye, pinkish-brown body, small blue-grey bill.",
    about: "Also called the Baldpate, after the male's white forehead.",
    colors: ["B8B4AC", "8A9AAE", "B78A6E", "B78A6E"],
    x: {
      weight: "0.5–1.3 kg", wingspan: "76–84 cm", lifespan: "Record 21 years",
      voice: "A wheezy three-note whistle, 'whee-WHEE-whew', like a squeaky toy.",
      facts: [
        "Like Gadwalls, they pirate plants from diving ducks and coots.",
        "They are among the first ducks to migrate south each autumn.",
      ],
    },
  },
  {
    id: "chiloe-wigeon", name: "Chiloé Wigeon", sci: "Mareca sibilatrix", group: "dabbling", status: "LC", len: "43–54",
    regions: "SA", habitat: "Lakes and marshes of southern South America and the Falklands.",
    marks: "White face and glossy green head, black-and-white scaled breast, orange flanks. Both sexes look alike.",
    about: "Pairs stay together year-round, unusual among ducks.",
    colors: ["1E5E4A", "5E6B78", "3A3A3A", "C57A3A"],
  },
  {
    id: "northern-shoveler", name: "Northern Shoveler", sci: "Spatula clypeata", group: "dabbling", status: "LC", len: "44–52",
    regions: "NA EU AS AF", habitat: "Shallow, muddy marshes and ponds rich in plankton.",
    marks: "Huge spoon-shaped black bill, green head, bright white breast and rusty-chestnut flanks. Yellow eyes.",
    about: "Its bill is lined with comb-like lamellae to strain tiny animals from the water.",
    colors: ["1E6B45", "2A2A2A", "F4F4F2", "B5562E"],
    x: {
      weight: "0.4–1.1 kg", wingspan: "70–84 cm", lifespan: "Record 20 years",
      voice: "Males give a hollow, knocking 'took-took'.",
      facts: [
        "Groups swim in tight circles to stir up food from the bottom, then sieve it.",
        "The bill has around 110 fine comb-like plates along each edge.",
      ],
    },
  },
  {
    id: "blue-winged-teal", name: "Blue-winged Teal", sci: "Spatula discors", group: "dabbling", status: "LC", len: "36–41",
    regions: "NA SA", habitat: "Shallow prairie ponds and marshes; winters to South America.",
    marks: "Slate-blue head with a bold white crescent in front of the eye, tan body with dark spots. Powder-blue forewing in flight.",
    about: "One of the longest migrations of any duck, some flying from Canada to Peru.",
    colors: ["55627A", "2A2A2A", "B59570", "A9875F"],
    x: {
      weight: "0.3–0.5 kg", wingspan: "58–63 cm", lifespan: "Record 23 years",
      voice: "Males give a high, thin whistled 'peew'.",
      facts: [
        "It is one of the last ducks to arrive in spring and the first to leave in autumn.",
        "That blue forewing patch is shared with its close relatives the Cinnamon Teal and shovelers.",
      ],
    },
  },
  {
    id: "cinnamon-teal", name: "Cinnamon Teal", sci: "Spatula cyanoptera", group: "dabbling", status: "LC", len: "35–48",
    regions: "NA SA", habitat: "Marshes and ponds of western North America and South America.",
    marks: "Deep cinnamon-red all over with a glowing red eye and long black bill.",
    about: "The only North American duck with separate breeding populations in both Americas.",
    colors: ["A8401F", "2A2A2A", "A8401F", "A8401F"],
  },
  {
    id: "garganey", name: "Garganey", sci: "Spatula querquedula", group: "dabbling", status: "LC", len: "37–41",
    regions: "EU AS AF", habitat: "Well-vegetated shallow pools; winters in tropical Africa and Asia.",
    marks: "Brown head with a long, bold white stripe curving from the eye to the nape; pale grey flanks.",
    about: "Unusually for a duck, it leaves Europe entirely in winter, crossing the Sahara.",
    colors: ["7A4E32", "2A2A2A", "9C7A5A", "B8BBBE"],
  },
  {
    id: "baikal-teal", name: "Baikal Teal", sci: "Sibirionetta formosa", group: "dabbling", status: "LC", len: "39–43",
    regions: "AS", habitat: "Siberian taiga pools; winters in huge flocks in South Korea.",
    marks: "Extraordinary face pattern: creamy-yellow and green swirls outlined in black. Pinkish spotted breast.",
    about: "Winter flocks in Korea can top a million birds, swirling like starlings.",
    colors: ["D8C070", "2A2A2A", "B78A7A", "A9AFB5"],
  },
  {
    id: "red-shoveler", name: "Red Shoveler", sci: "Spatula platalea", group: "dabbling", status: "LC", len: "45–56",
    regions: "SA", habitat: "Shallow lakes and marshes of southern South America.",
    marks: "Pale, spotted buff head, cinnamon-red body with black spots, large black shovel bill.",
    about: "The only shoveler with a pale head instead of a green one.",
    colors: ["D8C8A8", "2A2A2A", "B06040", "B06040"],
  },
  {
    id: "cape-shoveler", name: "Cape Shoveler", sci: "Spatula smithii", group: "dabbling", status: "LC", len: "51–53",
    regions: "AF", habitat: "Shallow fresh and brackish wetlands of southern Africa.",
    marks: "Greyish-brown speckled duck with a pale head and a big black shovel bill. Yellow eyes in males.",
    about: "A shoveler that has lost the bright colours of its northern cousin.",
    colors: ["B8AFA2", "2A2A2A", "7A6A58", "7A6A58"],
  },
  {
    id: "australasian-shoveler", name: "Australasian Shoveler", sci: "Spatula rhynchotis", group: "dabbling", status: "LC", len: "46–53",
    regions: "OC", habitat: "Well-vegetated wetlands in southern Australia and New Zealand.",
    marks: "Blue-grey head with a white crescent, chestnut flanks and a large spoon bill.",
    about: "Its head pattern closely resembles the Blue-winged Teal's, a hint of their close relationship.",
    colors: ["55627A", "2A2A2A", "8C6A48", "B06440"],
  },
  {
    id: "hottentot-teal", name: "Hottentot Teal", sci: "Spatula hottentota", group: "dabbling", status: "LC", len: "30–35",
    regions: "AF", habitat: "Reedy swamps and floodplains of eastern and southern Africa.",
    marks: "Tiny, with a dark cap, pale cheeks with a dark smudge, and a blue-grey bill.",
    about: "Also known as the Blue-billed Teal; one of the world's smallest ducks.",
    colors: ["E6D8BC", "6E88A8", "A58B6A", "A58B6A"],
  },
  {
    id: "silver-teal", name: "Silver Teal", sci: "Spatula versicolor", group: "dabbling", status: "LC", len: "38–48",
    regions: "SA", habitat: "Reedy marshes and lakes of southern South America.",
    marks: "Black cap over creamy cheeks, finely barred silver-grey flanks, blue bill with a yellow base.",
    about: "Its barred flanks shimmer silver in sunlight.",
    colors: ["F0E8D4", "6E9AC8", "C8B89C", "B6B8BA"],
  },
  {
    id: "puna-teal", name: "Puna Teal", sci: "Spatula puna", group: "dabbling", status: "LC", len: "48–51",
    regions: "SA", habitat: "High Andean lakes and marshes of Peru, Bolivia and Chile.",
    marks: "Black cap over white cheeks, grey barred body and a big bright blue bill without yellow.",
    about: "A high-altitude cousin of the Silver Teal.",
    colors: ["F4F2EE", "5A9AD8", "C8BCA8", "B6B8BA"],
  },
  {
    id: "crested-duck", name: "Crested Duck", sci: "Lophonetta specularioides", group: "dabbling", status: "LC", len: "51–61",
    regions: "SA", habitat: "High Andean lakes and cold Patagonian coasts.",
    marks: "Grey-brown with a shaggy crest down the back of the head, red eyes and a bronze-pink wing patch.",
    about: "Aggressive and territorial, it often chases other ducks off its patch.",
    colors: ["A89C8C", "3A3E44", "9C8C78", "9C8C78"],
  },
  {
    id: "spectacled-duck", name: "Spectacled Duck", sci: "Speculanas specularis", group: "dabbling", status: "NT", len: "46–54",
    regions: "SA", habitat: "Fast forest rivers of Chile and Argentina.",
    marks: "Dark brown with a white 'spectacle' patch in front of the eye and a white throat; bronze wing patch.",
    about: "Also called the Bronze-winged Duck; its call sounds like a dog barking.",
    colors: ["4A3A2C", "3A3E44", "6E5440", "6E5440"],
  },

  // ── Diving ducks ──────────────────────────────────────────────────
  {
    id: "canvasback", name: "Canvasback", sci: "Aythya valisineria", group: "diving", status: "LC", len: "48–56",
    regions: "NA", habitat: "Prairie marshes; winters on large lakes, bays and estuaries.",
    marks: "Long, sloping wedge-shaped profile from forehead to bill. Chestnut head, black breast and bright white 'canvas' back.",
    about: "Named for the canvas-white back; its scientific name honours wild celery, a favourite food.",
    colors: ["8B3A1F", "2A2A2A", "1E1E1E", "EDEDEA"],
    x: {
      weight: "0.9–1.6 kg", wingspan: "74–90 cm", lifespan: "Record 22 years",
      voice: "Mostly quiet; males give soft cooing calls in courtship.",
      facts: [
        "Among the fastest ducks, reaching about 90 km/h.",
        "Can dive to 9 m to dig up the tubers of wild celery.",
      ],
    },
  },
  {
    id: "redhead", name: "Redhead", sci: "Aythya americana", group: "diving", status: "LC", len: "42–54",
    regions: "NA", habitat: "Prairie potholes; winters on lagoons and bays such as the Laguna Madre.",
    marks: "Round rusty-red head, black breast, grey body, and a blue-grey bill with a white ring and black tip.",
    about: "Females often lay eggs in other ducks' nests, leaving them to raise the young.",
    colors: ["A8401F", "8A9AAE", "1E1E1E", "9EA3A8"],
    x: {
      weight: "0.6–1.6 kg", wingspan: "75–85 cm", lifespan: "Record 22 years",
      voice: "Courting males give a cat-like 'whee-ooo'.",
      facts: [
        "Compared with the Canvasback, it has a rounder head and a grey (not white) back.",
        "Up to 80% of the world's Redheads winter along the Gulf Coast of Texas and Mexico.",
      ],
    },
  },
  {
    id: "common-pochard", name: "Common Pochard", sci: "Aythya ferina", group: "diving", status: "VU", len: "42–49",
    regions: "EU AS AF", habitat: "Lakes and reservoirs; big winter flocks rest by day and feed at night.",
    marks: "Rusty-red head, black breast, pale grey body and a dark bill with a grey band.",
    about: "Once abundant across Europe, it has declined sharply and is now listed as Vulnerable.",
    colors: ["A8401F", "4A4F58", "1E1E1E", "C4C7CA"],
  },
  {
    id: "ring-necked-duck", name: "Ring-necked Duck", sci: "Aythya collaris", group: "diving", status: "LC", len: "37–46",
    regions: "NA", habitat: "Wooded ponds, bogs and small lakes.",
    marks: "Peaked purple-black head, black back, grey flanks with a white spur in front of the wing, and a grey bill with a white ring.",
    about: "The chestnut neck ring it is named after is almost impossible to see; look for the ringed bill instead.",
    colors: ["241A30", "8A9AAE", "1E1E1E", "A7AAAE"],
    x: {
      weight: "0.5–0.9 kg", wingspan: "61–63 cm", lifespan: "Record 20 years",
      voice: "Mostly silent; males give a low whistle during courtship.",
      facts: [
        "It prefers smaller, shallower ponds than other diving ducks.",
        "The white 'spur' at the front of the flanks is a quick identification clue.",
      ],
    },
  },
  {
    id: "ferruginous-duck", name: "Ferruginous Duck", sci: "Aythya nyroca", group: "diving", status: "NT", len: "38–42",
    regions: "EU AS AF", habitat: "Shallow, reedy lakes and fishponds.",
    marks: "Rich mahogany-brown all over with a white eye (male) and a white patch under the tail.",
    about: "'Ferruginous' means rust-coloured.",
    colors: ["6E2E1A", "4A4F58", "6E2E1A", "6E2E1A"],
  },
  {
    id: "baers-pochard", name: "Baer's Pochard", sci: "Aythya baeri", group: "diving", status: "CR", len: "41–47",
    regions: "AS", habitat: "Reedy lakes in northeast China and Russia; winters in China.",
    marks: "Glossy green-black head, white eye, chestnut breast, brown flanks with white at the front.",
    about: "Fewer than a thousand remain, making it one of the rarest ducks in the world.",
    colors: ["1E3A30", "4A4F58", "6E3A22", "7A5A40"],
  },
  {
    id: "madagascar-pochard", name: "Madagascar Pochard", sci: "Aythya innotata", group: "diving", status: "CR", len: "45",
    regions: "AF", habitat: "A single volcanic crater lake in northern Madagascar.",
    marks: "Dark chestnut-brown with a white eye in males and a white patch under the tail.",
    about: "Thought extinct until 22 birds were found in 2006; a captive programme is bringing it back.",
    colors: ["5E3020", "4A4F58", "5E3020", "5E3020"],
  },
  {
    id: "hardhead", name: "Hardhead", sci: "Aythya australis", group: "diving", status: "LC", len: "42–59",
    regions: "OC", habitat: "Deep, well-vegetated lakes and swamps in Australia.",
    marks: "Rich brown with a white eye (male), a white patch under the tail and a pale band near the bill tip.",
    about: "Also called the White-eyed Duck; the only true diving duck native to Australia.",
    colors: ["6A3E26", "3A3E44", "6A3E26", "6A3E26"],
  },
  {
    id: "new-zealand-scaup", name: "New Zealand Scaup", sci: "Aythya novaeseelandiae", group: "diving", status: "LC", len: "40–46",
    regions: "OC", habitat: "Deep, clear lakes in New Zealand.",
    marks: "Small, almost entirely black-brown duck with a bright yellow eye (male).",
    about: "Known in Māori as pāpango; it can dive for up to a minute.",
    colors: ["1E1A22", "4A5A7A", "1E1A22", "2A2428"],
  },
  {
    id: "tufted-duck", name: "Tufted Duck", sci: "Aythya fuligula", group: "diving", status: "LC", len: "40–47",
    regions: "EU AS AF", habitat: "Lakes, reservoirs, gravel pits and city park ponds.",
    marks: "Black with bright white flanks, a golden eye and a floppy tuft hanging off the back of the head.",
    about: "One of the commonest ducks on European park lakes.",
    colors: ["1E1A26", "8A9AAE", "1E1E1E", "F4F4F2"],
    x: {
      weight: "0.6–1.0 kg", wingspan: "65–72 cm", lifespan: "Record 24 years",
      voice: "Mostly silent; females give a growling 'kerr'.",
      facts: [
        "It spread across Europe in the 1800s thanks to the invasive zebra mussel, a favourite food.",
        "It often nests among gull and tern colonies for protection.",
      ],
    },
  },
  {
    id: "greater-scaup", name: "Greater Scaup", sci: "Aythya marila", group: "diving", status: "LC", len: "39–56",
    regions: "NA EU AS", habitat: "Tundra lakes; winters in big rafts on sheltered coasts and bays.",
    marks: "Rounded green-glossed black head, black breast, pale grey finely barred back, white flanks and a blue bill.",
    about: "Gathers in winter rafts of thousands of birds.",
    colors: ["1C3A2E", "8A9AAE", "1E1E1E", "E8E8E6"],
  },
  {
    id: "lesser-scaup", name: "Lesser Scaup", sci: "Aythya affinis", group: "diving", status: "LC", len: "38–45",
    regions: "NA", habitat: "Prairie and boreal wetlands; winters on lakes, reservoirs and bays.",
    marks: "Like the Greater Scaup but with a peaked, purple-glossed head and a smaller bill.",
    about: "The most abundant diving duck in North America.",
    colors: ["2A1E36", "8A9AAE", "1E1E1E", "D8D8D6"],
    x: {
      weight: "0.5–1.1 kg", wingspan: "68–78 cm", lifespan: "Record 18 years",
      voice: "A low 'scaup' call, which gave it its name.",
      facts: [
        "Head shape is the best clue: a bump at the back of the crown on the Lesser, a smooth dome on the Greater.",
        "They breed later than most ducks, waiting for amphipods to become plentiful.",
      ],
    },
  },
  {
    id: "red-crested-pochard", name: "Red-crested Pochard", sci: "Netta rufina", group: "diving", status: "LC", len: "53–57",
    regions: "EU AS AF", habitat: "Large reedy lakes with plenty of submerged plants.",
    marks: "Big, bushy orange head, coral-red bill, black breast and white flanks.",
    about: "Males court females by offering them morsels of food.",
    colors: ["E07A2A", "D9362F", "1E1E1E", "EDEAE4"],
  },
  {
    id: "rosy-billed-pochard", name: "Rosy-billed Pochard", sci: "Netta peposaca", group: "diving", status: "LC", len: "53–57",
    regions: "SA", habitat: "Marshes and lakes of southern South America.",
    marks: "Purplish-black head and breast, grey flanks and a bright rosy-red bill with a knob at the base.",
    about: "Despite being a pochard, it feeds more like a dabbler, rarely diving.",
    colors: ["2A1E30", "E0506A", "1E1E1E", "9EA0A4"],
  },
  {
    id: "southern-pochard", name: "Southern Pochard", sci: "Netta erythrophthalma", group: "diving", status: "LC", len: "48–51",
    regions: "AF SA", habitat: "Open freshwater lakes and dams.",
    marks: "Dark brown with a purplish head, red eye and blue-grey bill.",
    about: "Lives in two widely separated populations, in Africa and South America.",
    colors: ["3A2230", "6E88A8", "3A2A26", "5A3E30"],
  },
  {
    id: "pink-headed-duck", name: "Pink-headed Duck", sci: "Rhodonessa caryophyllacea", group: "diving", status: "CR", len: "60",
    regions: "AS", habitat: "Formerly overgrown pools in the forests of India, Bangladesh and Myanmar.",
    marks: "Long neck with a bright pink head and dark chocolate-brown body.",
    about: "Not reliably seen since 1949 and possibly extinct, though searches continue in Myanmar.",
    colors: ["E88AA8", "E0A0B0", "3A2A22", "3A2A22"],
  },

  // ── Sea ducks ─────────────────────────────────────────────────────
  {
    id: "common-eider", name: "Common Eider", sci: "Somateria mollissima", group: "sea", status: "NT", len: "50–71",
    regions: "NA EU AS", habitat: "Rocky northern coasts and islands; rarely inland.",
    marks: "Big and wedge-billed: white back and breast, black belly and crown, pale green nape. Females are barred brown.",
    about: "Its down is still collected from nests to fill the warmest duvets.",
    colors: ["F4F4EE", "9EAA88", "F2E6D8", "1E1E1E"],
    x: {
      weight: "1.2–2.9 kg", wingspan: "95–105 cm", lifespan: "Record 36 years",
      voice: "Males coo a crooning 'ah-OOO-ah' like a surprised person.",
      facts: [
        "The largest duck in the Northern Hemisphere.",
        "Females form crèches, taking turns guarding groups of ducklings.",
      ],
    },
  },
  {
    id: "king-eider", name: "King Eider", sci: "Somateria spectabilis", group: "sea", status: "LC", len: "47–63",
    regions: "NA EU AS", habitat: "Arctic tundra; winters at sea along the ice edge.",
    marks: "Pastel blue-grey crown, green cheeks, and a huge orange frontal shield on the red bill. Black body with white front.",
    about: "Can dive to more than 50 m for shellfish.",
    colors: ["8AA4C8", "F07A30", "F2DCC0", "1E1E1E"],
  },
  {
    id: "spectacled-eider", name: "Spectacled Eider", sci: "Somateria fischeri", group: "sea", status: "NT", len: "52–57",
    regions: "NA AS", habitat: "Arctic coastal tundra; winters in holes in the Bering Sea ice.",
    marks: "Pale green head with large white 'goggles' ringed in black; black breast.",
    about: "The whole world population winters packed into a few openings in the Bering Sea pack ice.",
    colors: ["A8C8A0", "F07A30", "1E1E1E", "EDEDEA"],
  },
  {
    id: "stellers-eider", name: "Steller's Eider", sci: "Polysticta stelleri", group: "sea", status: "VU", len: "43–47",
    regions: "NA AS EU", habitat: "Arctic tundra pools; winters on rocky coasts of Alaska and Norway.",
    marks: "Smallest eider: white head with a green knob, black eye patch and chin, buff-orange underparts.",
    about: "Moves in tight, synchronised flocks that dive together.",
    colors: ["F4F4EE", "5E6B78", "D8955A", "1E1E1E"],
  },
  {
    id: "harlequin-duck", name: "Harlequin Duck", sci: "Histrionicus histrionicus", group: "sea", status: "LC", len: "33–54",
    regions: "NA EU AS", habitat: "Breeds on fast mountain streams; winters on surf-pounded rocky coasts.",
    marks: "Slate-blue with bold white stripes and spots outlined in black, and chestnut flanks.",
    about: "Many adults show healed bone fractures from life in whitewater and crashing surf.",
    colors: ["3E4A6A", "4A4F58", "3E4A6A", "A0522D"],
    x: {
      weight: "0.5–0.7 kg", wingspan: "56–66 cm", lifespan: "Record 18 years",
      voice: "High, mouse-like squeaks, earning it the nickname 'sea mouse'.",
      facts: [
        "It walks along the bottom of fast streams, facing the current, to pick insect larvae off rocks.",
        "Named after Harlequin, the colourfully costumed character of Italian comedy.",
      ],
    },
  },
  {
    id: "surf-scoter", name: "Surf Scoter", sci: "Melanitta perspicillata", group: "sea", status: "LC", len: "43–53",
    regions: "NA", habitat: "Boreal lakes; winters in the surf along Pacific and Atlantic coasts.",
    marks: "All black with white patches on forehead and nape and a big clown-like orange, white and black bill.",
    about: "Nicknamed the 'skunk-head coot' for its white head patches.",
    colors: ["1E1E1E", "F07A30", "1E1E1E", "1E1E1E"],
  },
  {
    id: "white-winged-scoter", name: "White-winged Scoter", sci: "Melanitta deglandi", group: "sea", status: "LC", len: "51–58",
    regions: "NA", habitat: "Boreal lakes; winters on coastal waters.",
    marks: "Black with a white 'comma' around the eye, white wing patches and an orange-tipped knobbed bill.",
    about: "The largest scoter, able to swallow clams whole.",
    colors: ["1E1E1E", "E8703A", "1E1E1E", "1E1E1E"],
  },
  {
    id: "stejnegers-scoter", name: "Stejneger's Scoter", sci: "Melanitta stejnegeri", group: "sea", status: "LC", len: "51–58",
    regions: "AS", habitat: "Siberian lakes; winters along East Asian coasts.",
    marks: "Black with a white eye comma, white wing patch and a steeply humped red-and-yellow bill.",
    about: "Recently split from the White-winged Scoter as a separate Asian species.",
    colors: ["1E1E1E", "D84A3A", "1E1E1E", "1E1E1E"],
  },
  {
    id: "velvet-scoter", name: "Velvet Scoter", sci: "Melanitta fusca", group: "sea", status: "VU", len: "51–58",
    regions: "EU AS", habitat: "Northern lakes and tundra; winters in the Baltic and North Sea.",
    marks: "Velvety black with a white crescent under the eye, white wing patches and a yellow-sided bill.",
    about: "Oil spills and fishing nets in the Baltic have driven a steep decline.",
    colors: ["1E1E1E", "E8B040", "1E1E1E", "1E1E1E"],
  },
  {
    id: "common-scoter", name: "Common Scoter", sci: "Melanitta nigra", group: "sea", status: "LC", len: "44–54",
    regions: "EU AS", habitat: "Tundra and moorland lakes; winters in large flocks offshore.",
    marks: "Entirely black male with a yellow patch on top of the black bill.",
    about: "Often seen as long, low lines of black ducks flying over the sea.",
    colors: ["1E1E1E", "2A2A2A", "1E1E1E", "1E1E1E"],
  },
  {
    id: "black-scoter", name: "Black Scoter", sci: "Melanitta americana", group: "sea", status: "NT", len: "43–49",
    regions: "NA AS", habitat: "Tundra lakes; winters along North American coasts.",
    marks: "Entirely black male with a big, bulbous yellow-orange knob on the bill.",
    about: "Males give a mournful, whistled 'peeew' that carries across the water.",
    colors: ["1E1E1E", "F2B020", "1E1E1E", "1E1E1E"],
  },
  {
    id: "long-tailed-duck", name: "Long-tailed Duck", sci: "Clangula hyemalis", group: "sea", status: "VU", len: "36–60",
    regions: "NA EU AS", habitat: "Arctic tundra pools; winters on cold northern seas and the Great Lakes.",
    marks: "Winter male is white and pale grey with dark cheek patch, black breast and very long black tail streamers. Pink band on the bill.",
    about: "Dives deeper than almost any other duck, down to 60 m or more.",
    colors: ["F4F2EE", "E88AA8", "2A2A2A", "D8D4CC"],
    x: {
      weight: "0.5–1.0 kg", wingspan: "65–82 cm", lifespan: "Record 22 years",
      voice: "Noisy, yodelling 'ow-owdle-ow' calls carrying over the sea.",
      facts: [
        "It uses its wings to 'fly' underwater when diving.",
        "It moults so often that it has different plumages in summer, autumn and winter.",
      ],
    },
  },
  {
    id: "bufflehead", name: "Bufflehead", sci: "Bucephala albeola", group: "sea", status: "LC", len: "32–40",
    regions: "NA", habitat: "Wooded lakes where it nests in old flicker holes; winters on bays and lakes.",
    marks: "Tiny, with a big puffy head: glossy purple-green black with a huge white wedge behind the eye, white body.",
    about: "Small enough to nest in old Northern Flicker holes in trees.",
    colors: ["2A2438", "8A9AAE", "F4F4F2", "F4F4F2"],
    x: {
      weight: "0.3–0.6 kg", wingspan: "54–61 cm", lifespan: "Record 18 years",
      voice: "Mostly quiet; males give a squeaky whistle.",
      facts: [
        "North America's smallest diving duck.",
        "Its name comes from 'buffalo-head', for the oversized puffy head.",
      ],
    },
  },
  {
    id: "common-goldeneye", name: "Common Goldeneye", sci: "Bucephala clangula", group: "sea", status: "LC", len: "40–51",
    regions: "NA EU AS", habitat: "Boreal lakes and rivers; winters on lakes, rivers and coasts.",
    marks: "Triangular green-black head, bright yellow eye, round white spot between eye and bill, and a white body.",
    about: "Its wings whistle loudly in flight, earning it the nickname 'whistler'.",
    colors: ["1C3A2E", "2A2A2A", "F4F4F2", "F4F4F2"],
    x: {
      weight: "0.6–1.3 kg", wingspan: "77–83 cm", lifespan: "Record 20 years",
      voice: "Males give a nasal 'bee-bzzt' during a head-throwing courtship display.",
      facts: [
        "Ducklings leap from tree-hole nests up to 15 m high, the day after hatching.",
        "In courtship the male throws his head back until it touches his tail.",
      ],
    },
  },
  {
    id: "barrows-goldeneye", name: "Barrow's Goldeneye", sci: "Bucephala islandica", group: "sea", status: "LC", len: "42–53",
    regions: "NA EU", habitat: "Mountain lakes of western North America, Iceland and Labrador.",
    marks: "Purple-glossed head with a steep forehead and a white crescent (not a spot) in front of the eye; more black on the back.",
    about: "Iceland's Lake Mývatn holds the only European population.",
    colors: ["2A2240", "2A2A2A", "F4F4F2", "3A3A3A"],
  },
  {
    id: "labrador-duck", name: "Labrador Duck", sci: "Camptorhynchus labradorius", group: "sea", status: "EX", len: "50–56",
    regions: "NA", habitat: "Formerly sandy bays and estuaries of the northeast US coast.",
    marks: "Black-and-white pied male with a white head, black crown stripe and a soft, flattened bill.",
    about: "The first North American bird to go extinct after 1500; the last one was shot in about 1878.",
    colors: ["F4F4EE", "4A4F58", "F4F4EE", "1E1E1E"],
  },

  // ── Mergansers ────────────────────────────────────────────────────
  {
    id: "hooded-merganser", name: "Hooded Merganser", sci: "Lophodytes cucullatus", group: "merganser", status: "LC", len: "40–49",
    regions: "NA", habitat: "Wooded ponds, beaver swamps and small rivers.",
    marks: "A black crest with a huge white fan it can raise and lower, gold eye, chestnut flanks and a thin black bill.",
    about: "Has an extra eyelid, the nictitating membrane, that works like swimming goggles.",
    colors: ["1E1E1E", "1E1E1E", "F4F4F2", "B5652D"],
    x: {
      weight: "0.45–0.9 kg", wingspan: "60–66 cm", lifespan: "Record 14 years",
      voice: "Males give a low, frog-like rolling croak.",
      facts: [
        "It changes the shape of its lens to see clearly underwater.",
        "Females sometimes lay eggs in Wood Duck nest boxes, and vice versa.",
      ],
    },
  },
  {
    id: "common-merganser", name: "Common Merganser (Goosander)", sci: "Mergus merganser", group: "merganser", status: "LC", len: "54–71",
    regions: "NA EU AS", habitat: "Clear rivers and large lakes near forest.",
    marks: "Long and sleek: dark green head, narrow red serrated bill, white body often washed salmon-pink.",
    about: "The largest merganser; ducklings ride on their mother's back.",
    colors: ["1E4A38", "D9362F", "F2E8E0", "F2E8E0"],
    x: {
      weight: "0.9–2.1 kg", wingspan: "78–94 cm", lifespan: "Record 13 years",
      voice: "Low, twanging croaks from males; harsh 'karr' from females.",
      facts: [
        "Its saw-toothed bill gives the group the nickname 'sawbills'.",
        "Groups sometimes hunt together, driving fish into shallow water.",
      ],
    },
  },
  {
    id: "red-breasted-merganser", name: "Red-breasted Merganser", sci: "Mergus serrator", group: "merganser", status: "LC", len: "51–62",
    regions: "NA EU AS", habitat: "Coastal bays and large lakes; breeds on northern rivers and lakes.",
    marks: "Shaggy double crest on a green head, white collar, streaky rusty breast, thin red bill.",
    about: "One of the fastest ducks, clocked at over 100 km/h in level flight.",
    colors: ["1E4A38", "D9362F", "A8603A", "9EA0A4"],
  },
  {
    id: "smew", name: "Smew", sci: "Mergellus albellus", group: "merganser", status: "LC", len: "38–44",
    regions: "EU AS", habitat: "Northern forest lakes; winters on lakes and reservoirs.",
    marks: "Brilliant white with a black eye mask and thin black lines, like cracked ice. Small grey bill.",
    about: "Birdwatchers call the male the 'white nun'.",
    colors: ["F4F4F2", "4A4F58", "F4F4F2", "E8E8E6"],
  },
  {
    id: "scaly-sided-merganser", name: "Scaly-sided Merganser", sci: "Mergus squamatus", group: "merganser", status: "EN", len: "52–62",
    regions: "AS", habitat: "Fast, clear rivers in old-growth forests of Russia and northeast China.",
    marks: "Green-black head with a long shaggy crest, red bill and grey scaly flanks.",
    about: "Nests in tree holes along rivers, so logging threatens it directly.",
    colors: ["1E4A38", "D9362F", "F4F2EE", "B8B8B8"],
  },
  {
    id: "brazilian-merganser", name: "Brazilian Merganser", sci: "Mergus octosetaceus", group: "merganser", status: "CR", len: "49–56",
    regions: "SA", habitat: "Clear rapids in the Cerrado of Brazil.",
    marks: "Dark green head with a long thin crest, black bill, grey body.",
    about: "Fewer than 250 adults remain, among the rarest waterfowl anywhere.",
    colors: ["1E3A30", "1E1E1E", "8A8C90", "8A8C90"],
  },

  // ── Perching ducks ────────────────────────────────────────────────
  {
    id: "wood-duck", name: "Wood Duck", sci: "Aix sponsa", group: "perching", status: "LC", len: "47–54",
    regions: "NA", habitat: "Wooded swamps, beaver ponds and slow rivers with trees nearby.",
    marks: "Iridescent green-and-purple crested head with bold white stripes, red eye, red-and-white bill, chestnut breast.",
    about: "Nearly wiped out around 1900, it recovered thanks to protection and nest boxes.",
    colors: ["1E6B55", "D9362F", "8B3A2A", "C9A66E"],
    x: {
      weight: "0.45–0.9 kg", wingspan: "66–73 cm", lifespan: "Record 22 years",
      voice: "Females give a rising, squealing 'oo-EEK'.",
      facts: [
        "Ducklings jump from nests up to 15 m high without getting hurt.",
        "Sharp claws let it perch on branches, unusual for a duck.",
      ],
    },
  },
  {
    id: "mandarin-duck", name: "Mandarin Duck", sci: "Aix galericulata", group: "perching", status: "LC", len: "41–49",
    regions: "AS EU", habitat: "Wooded lakes and rivers; introduced populations live in Britain and Europe.",
    marks: "Orange 'sails' raised on the back, orange whisker-like cheek plumes, white eye stripe, red bill, purple breast.",
    about: "A symbol of devoted love in China, Korea and Japan.",
    colors: ["E08A3A", "D9362F", "5A2A5A", "C9A66E"],
    x: {
      weight: "0.4–0.7 kg", wingspan: "65–75 cm", lifespan: "Up to 10 years",
      voice: "Males give a sharp whistle; females a soft clucking.",
      facts: [
        "The orange 'sails' are enlarged tertial wing feathers.",
        "There may now be more Mandarins in Britain than in parts of their native China.",
      ],
    },
  },
  {
    id: "muscovy-duck", name: "Muscovy Duck", sci: "Cairina moschata", group: "perching", status: "LC", len: "66–84",
    regions: "NA SA", habitat: "Forest rivers and swamps of Central and South America; feral birds live in parks worldwide.",
    marks: "Big and heavy. Wild birds are glossy black-green with white wing patches; domestic and feral birds are pied black-and-white with bare red warty skin (caruncles) on the face.",
    about: "Not descended from the Mallard: it is the only domesticated duck from the Americas.",
    colors: ["1E2A22", "E08A8A", "1E2A22", "1E2A22"],
    x: {
      weight: "1.1–4 kg (domestic males up to 7 kg)", wingspan: "137–152 cm", lifespan: "8–12 years",
      voice: "Nearly silent. Males hiss; females give quiet trills.",
      facts: [
        "Muscovies don't quack. They communicate with hisses, trills and tail wagging.",
        "Crossing a Muscovy with a Mallard produces a sterile hybrid called a mulard.",
      ],
    },
  },
  {
    id: "white-winged-duck", name: "White-winged Duck", sci: "Asarcornis scutulata", group: "perching", status: "EN", len: "66–81",
    regions: "AS", habitat: "Swampy pools in dense tropical forest from India to Sumatra.",
    marks: "Large and dark with a pale, black-speckled head and white wing patches.",
    about: "Its honking calls at dusk earned it the nickname 'wood ghost'.",
    colors: ["E8E4DA", "E8B040", "3A3226", "3A3226"],
  },
  {
    id: "hartlaubs-duck", name: "Hartlaub's Duck", sci: "Pteronetta hartlaubii", group: "perching", status: "LC", len: "56–58",
    regions: "AF", habitat: "Forest streams and pools of West and Central Africa.",
    marks: "Chestnut body, black head with a white forehead patch and pale blue wing panels.",
    about: "Shy and rarely seen in its dense rainforest habitat.",
    colors: ["1E1E1E", "2A2A2A", "8B3A1F", "8B3A1F"],
  },
  {
    id: "knob-billed-duck", name: "Knob-billed Duck", sci: "Sarkidiornis melanotos", group: "perching", status: "LC", len: "56–76",
    regions: "AF AS", habitat: "Tropical swamps, floodplains and wooded rivers.",
    marks: "White head speckled black, glossy blue-black back, and a large fleshy black knob on the male's bill.",
    about: "The knob swells during the breeding season.",
    colors: ["F4F2EE", "1E1E1E", "F4F2EE", "1E2A3A"],
  },
  {
    id: "comb-duck", name: "Comb Duck", sci: "Sarkidiornis sylvicola", group: "perching", status: "LC", len: "56–76",
    regions: "SA NA", habitat: "Tropical swamps and wooded rivers of South America.",
    marks: "Like the Knob-billed Duck with black-flanked sides and a big comb on the bill.",
    about: "Split from the Old World Knob-billed Duck as a separate American species.",
    colors: ["F4F2EE", "1E1E1E", "F4F2EE", "1E2A3A"],
  },
  {
    id: "maned-duck", name: "Maned Duck (Australian Wood Duck)", sci: "Chenonetta jubata", group: "perching", status: "LC", len: "45–51",
    regions: "OC", habitat: "Grassland near water, farm dams, golf courses and suburban parks in Australia.",
    marks: "Brown head with a short dark mane, speckled grey-brown breast, grey body. Short goose-like bill.",
    about: "Grazes on grass like a small goose and often perches on branches.",
    colors: ["6A4A32", "2A2A2A", "B8A898", "9EA0A4"],
  },
  {
    id: "brazilian-teal", name: "Brazilian Teal", sci: "Amazonetta brasiliensis", group: "perching", status: "LC", len: "35–40",
    regions: "SA", habitat: "Ponds and marshes in South American lowlands.",
    marks: "Warm brown with a pale grey cheek, bright red bill and legs (male) and an iridescent blue-green wing flash.",
    about: "Pairs often stay together for years.",
    colors: ["9C8468", "D9362F", "8A6A48", "8A6A48"],
  },
  {
    id: "ringed-teal", name: "Ringed Teal", sci: "Callonetta leucophrys", group: "perching", status: "LC", len: "35–38",
    regions: "SA", habitat: "Wooded swamps of Paraguay, Bolivia, Brazil and Argentina.",
    marks: "Chestnut back, pink spotted breast, grey flanks, black ring on the nape and a blue-grey bill.",
    about: "A tiny duck that nests in tree holes and parakeet nests.",
    colors: ["CBC6C0", "6E88A8", "E0B0A8", "A8603A"],
  },
  {
    id: "cotton-pygmy-goose", name: "Cotton Pygmy Goose", sci: "Nettapus coromandelianus", group: "perching", status: "LC", len: "30–37",
    regions: "AS OC", habitat: "Lily-covered ponds and lakes of South and Southeast Asia.",
    marks: "Tiny and mostly white, with a black cap, dark breast band and short goose-like bill.",
    about: "Despite the name it is a duck, one of the smallest in the world.",
    colors: ["F4F4F2", "2A2A2A", "F4F4F2", "F4F4F2"],
  },
  {
    id: "african-pygmy-goose", name: "African Pygmy Goose", sci: "Nettapus auritus", group: "perching", status: "LC", len: "30–33",
    regions: "AF", habitat: "Quiet waters with water lilies in sub-Saharan Africa.",
    marks: "Tiny: white face, green neck patch outlined in black, orange flanks and a yellow bill.",
    about: "Africa's smallest duck; it feeds mainly on water-lily seeds.",
    colors: ["F4F4F2", "F2C230", "E08A3A", "E08A3A"],
  },
  {
    id: "green-pygmy-goose", name: "Green Pygmy Goose", sci: "Nettapus pulchellus", group: "perching", status: "LC", len: "30–36",
    regions: "OC", habitat: "Lily-covered lagoons of northern Australia and New Guinea.",
    marks: "Tiny, glossy dark green with white cheeks and scalloped white flanks.",
    about: "It rarely comes to land, feeding among floating water lilies.",
    colors: ["1E4A38", "2A2A2A", "F4F2EE", "3A5A48"],
  },

  // ── Whistling ducks ───────────────────────────────────────────────
  {
    id: "black-bellied-whistling-duck", name: "Black-bellied Whistling Duck", sci: "Dendrocygna autumnalis", group: "whistling", status: "LC", len: "47–56",
    regions: "NA SA", habitat: "Freshwater ponds, rice fields and golf courses; often perches in trees.",
    marks: "Long pink legs, bright coral-pink bill, grey face, chestnut body and black belly. Bold white wing stripe in flight.",
    about: "Pairs often mate for life and share incubation duties.",
    colors: ["8A8C90", "F0708A", "A0522D", "1E1E1E"],
    x: {
      weight: "0.65–1 kg", wingspan: "76–94 cm", lifespan: "Record 8 years",
      voice: "A squealing, many-noted whistle, 'pe-che-che-ne'.",
      facts: [
        "Nicknamed the 'tree duck' because it perches and nests in trees.",
        "Its range has expanded rapidly northwards through the southern USA.",
      ],
    },
  },
  {
    id: "fulvous-whistling-duck", name: "Fulvous Whistling Duck", sci: "Dendrocygna bicolor", group: "whistling", status: "LC", len: "45–53",
    regions: "NA SA AF AS", habitat: "Rice fields, shallow marshes and lakes.",
    marks: "Tawny-orange body with a dark back, creamy stripes along the flanks and a white rump band in flight.",
    about: "Lives on four continents, yet the populations are genetically very similar.",
    colors: ["C8844A", "3A3E44", "C8844A", "C8844A"],
  },
  {
    id: "white-faced-whistling-duck", name: "White-faced Whistling Duck", sci: "Dendrocygna viduata", group: "whistling", status: "LC", len: "38–48",
    regions: "AF SA", habitat: "Lakes, dams and floodplains in Africa and South America.",
    marks: "Striking white face against a black head, chestnut breast and barred flanks.",
    about: "Flocks can number in the thousands and whistle constantly.",
    colors: ["F4F4F2", "2A2A2A", "8B3A1F", "6A5A4A"],
  },
  {
    id: "plumed-whistling-duck", name: "Plumed Whistling Duck", sci: "Dendrocygna eytoni", group: "whistling", status: "LC", len: "40–60",
    regions: "OC", habitat: "Grasslands near water in northern and eastern Australia.",
    marks: "Pale brown with long, cream, black-edged plumes standing up from the flanks; pink bill.",
    about: "Feeds mostly on land, grazing at night.",
    colors: ["C8B89C", "E0A0A8", "B08A62", "B08A62"],
  },
  {
    id: "spotted-whistling-duck", name: "Spotted Whistling Duck", sci: "Dendrocygna guttata", group: "whistling", status: "LC", len: "43–50",
    regions: "AS OC", habitat: "Lowland swamps and lagoons from the Philippines to New Guinea.",
    marks: "Grey face, brown breast and flanks covered in white spots.",
    about: "Roosts in trees during the day.",
    colors: ["A8A49C", "3A3E44", "8A6A48", "8A6A48"],
  },
  {
    id: "wandering-whistling-duck", name: "Wandering Whistling Duck", sci: "Dendrocygna arcuata", group: "whistling", status: "LC", len: "55–60",
    regions: "AS OC", habitat: "Lagoons and swamps from Indonesia to northern Australia.",
    marks: "Dark cap, chestnut body with black-and-cream flank plumes.",
    about: "Dives for food more than other whistling ducks.",
    colors: ["C8A882", "2A2A2A", "A0522D", "A0522D"],
  },
  {
    id: "lesser-whistling-duck", name: "Lesser Whistling Duck", sci: "Dendrocygna javanica", group: "whistling", status: "LC", len: "38–42",
    regions: "AS", habitat: "Paddies, tanks and wetlands across South and Southeast Asia.",
    marks: "Small, chestnut-brown with a dark cap, grey bill and reddish upperwing patch.",
    about: "Its wings make a whistling sound in flight, along with its wheezy calls.",
    colors: ["B89A78", "3A3E44", "A0522D", "8A5A38"],
  },
  {
    id: "west-indian-whistling-duck", name: "West Indian Whistling Duck", sci: "Dendrocygna arborea", group: "whistling", status: "NT", len: "48–58",
    regions: "NA", habitat: "Mangroves and swamps in the Caribbean.",
    marks: "The largest whistling duck: dark brown with black-and-white spotted flanks and a pale throat.",
    about: "Feeds at night on royal palm fruit and grain.",
    colors: ["B89A78", "2A2A2A", "7A5A3E", "5A4232"],
  },
  {
    id: "white-backed-duck", name: "White-backed Duck", sci: "Thalassornis leuconotus", group: "whistling", status: "LC", len: "38–40",
    regions: "AF", habitat: "Quiet, lily-covered lakes in sub-Saharan Africa.",
    marks: "Hunched, barred brown duck with a pale spot at the base of the bill. The white back shows only in flight.",
    about: "A strong diver related to the whistling ducks.",
    colors: ["9C7C58", "3A3E44", "8A6A48", "7A5A3E"],
  },

  // ── Stiff-tailed ducks ────────────────────────────────────────────
  {
    id: "ruddy-duck", name: "Ruddy Duck", sci: "Oxyura jamaicensis", group: "stifftail", status: "LC", len: "35–43",
    regions: "NA SA", habitat: "Marshy ponds with emergent plants; winters on lakes and bays.",
    marks: "Breeding male is bright chestnut with a black cap, big white cheek and sky-blue bill, tail often cocked up.",
    about: "Its eggs are huge for its size; a clutch can outweigh the female.",
    colors: ["F4F4F2", "4AA0E0", "A8401F", "A8401F"],
    x: {
      weight: "0.3–0.8 kg", wingspan: "56–62 cm", lifespan: "Record 13 years",
      voice: "Males court with a 'bubbling' display, drumming the bill on the chest to make bubbles.",
      facts: [
        "It rarely walks on land because its legs are set so far back.",
        "Introduced to Britain, it spread to Spain and threatened the White-headed Duck through hybridisation.",
      ],
    },
  },
  {
    id: "white-headed-duck", name: "White-headed Duck", sci: "Oxyura leucocephala", group: "stifftail", status: "EN", len: "43–48",
    regions: "EU AS AF", habitat: "Shallow, reedy lakes in Spain, North Africa and Central Asia.",
    marks: "White face, swollen bright blue bill, chestnut body and a stiff, often cocked tail.",
    about: "Spain's population grew from 22 birds in 1977 to thousands today.",
    colors: ["F4F4F2", "4A90D8", "A0603A", "A0603A"],
  },
  {
    id: "andean-duck", name: "Andean Duck", sci: "Oxyura ferruginea", group: "stifftail", status: "LC", len: "42–48",
    regions: "SA", habitat: "High Andean lakes from Colombia to Chile.",
    marks: "Like a Ruddy Duck but with an all-black head and no white cheek.",
    about: "Sometimes treated as a subspecies of the Ruddy Duck.",
    colors: ["1E1E1E", "4AA0E0", "A0401F", "A0401F"],
  },
  {
    id: "maccoa-duck", name: "Maccoa Duck", sci: "Oxyura maccoa", group: "stifftail", status: "VU", len: "46–51",
    regions: "AF", habitat: "Shallow lakes and dams in East and southern Africa.",
    marks: "Black head, chestnut body and a cobalt-blue bill; tail often held flat on the water.",
    about: "Males hold territories and mate with several females.",
    colors: ["1E1E1E", "3A70D8", "8B3A1F", "8B3A1F"],
  },
  {
    id: "argentine-lake-duck", name: "Argentine Lake Duck", sci: "Oxyura vittata", group: "stifftail", status: "LC", len: "36–46",
    regions: "SA", habitat: "Reedy lakes of southern South America.",
    marks: "Black head, chestnut body and a bright blue bill, like a small Ruddy Duck.",
    about: "Holds the record for the longest bird penis relative to body size, up to 42 cm.",
    colors: ["1E1E1E", "4AA0E0", "8B3A1F", "8B3A1F"],
  },
  {
    id: "blue-billed-duck", name: "Blue-billed Duck", sci: "Oxyura australis", group: "stifftail", status: "LC", len: "36–44",
    regions: "OC", habitat: "Deep, reedy wetlands of southern Australia.",
    marks: "Black head, chestnut body and a sky-blue bill; very rarely leaves the water.",
    about: "It almost never comes onto land, even building floating nests.",
    colors: ["1E1E1E", "4AA0E0", "7A3A1F", "7A3A1F"],
  },
  {
    id: "masked-duck", name: "Masked Duck", sci: "Nomonyx dominicus", group: "stifftail", status: "LC", len: "30–36",
    regions: "NA SA", habitat: "Densely vegetated tropical ponds and marshes.",
    marks: "Black face mask, rusty body spotted black, and a blue bill.",
    about: "So secretive that it's one of the most sought-after ducks by birders in Texas.",
    colors: ["1E1E1E", "4A90D8", "A8603A", "A8603A"],
  },
  {
    id: "black-headed-duck", name: "Black-headed Duck", sci: "Heteronetta atricapilla", group: "stifftail", status: "LC", len: "35–40",
    regions: "SA", habitat: "Marshes of Argentina, Paraguay, Uruguay and Chile.",
    marks: "Black head, brown speckled body, grey bill with a reddish base.",
    about: "The only duck that never raises its own young: it lays its eggs in the nests of coots, gulls and other birds.",
    colors: ["1E1E1E", "4A4F58", "7A5A3E", "7A5A3E"],
  },
  {
    id: "musk-duck", name: "Musk Duck", sci: "Biziura lobata", group: "stifftail", status: "LC", len: "55–66",
    regions: "OC", habitat: "Deep lakes, swamps and sheltered bays in southern Australia.",
    marks: "Dark grey and heavy, with a big leathery lobe hanging under the male's bill and a spiky tail.",
    about: "Males smell of musk in the breeding season, and captive birds have learned to mimic human speech.",
    colors: ["3A3A36", "2A2A2A", "4A4A44", "4A4A44"],
  },

  // ── Shelducks & specialists ───────────────────────────────────────
  {
    id: "common-shelduck", name: "Common Shelduck", sci: "Tadorna tadorna", group: "shelduck", status: "LC", len: "58–67",
    regions: "EU AS AF", habitat: "Estuaries, mudflats and salt marshes; nests in rabbit burrows.",
    marks: "Goose-like: bottle-green head, bright red bill (with a knob in males), white body with a broad chestnut breast band.",
    about: "Many European shelducks fly to the Wadden Sea each summer for a mass moult.",
    colors: ["1E4A38", "D9362F", "A0522D", "F4F4F2"],
    x: {
      weight: "0.8–1.5 kg", wingspan: "100–133 cm", lifespan: "Record 24 years",
      voice: "Males whistle; females give a rapid, laughing 'ak-ak-ak'.",
      facts: [
        "It sweeps its bill side to side through wet mud to catch tiny Hydrobia snails.",
        "Ducklings from many families gather into big crèches watched by a few adults.",
      ],
    },
  },
  {
    id: "ruddy-shelduck", name: "Ruddy Shelduck", sci: "Tadorna ferruginea", group: "shelduck", status: "LC", len: "58–70",
    regions: "EU AS AF", habitat: "Steppe lakes, rivers and high-altitude wetlands up to 5,000 m.",
    marks: "Rich orange-chestnut body, paler buff head, black tail and a thin black neck collar in breeding males. White wing panels in flight.",
    about: "Considered sacred by Buddhists; common in Tibet and Mongolia.",
    colors: ["E8C8A0", "1E1E1E", "C8743A", "C8743A"],
  },
  {
    id: "south-african-shelduck", name: "South African Shelduck", sci: "Tadorna cana", group: "shelduck", status: "LC", len: "61–66",
    regions: "AF", habitat: "Shallow lakes and dams in southern Africa.",
    marks: "Chestnut body with a grey head; females have a white face.",
    about: "Also called the Cape Shelduck; nests in aardvark burrows.",
    colors: ["9EA0A4", "1E1E1E", "C8743A", "B8683A"],
  },
  {
    id: "australian-shelduck", name: "Australian Shelduck", sci: "Tadorna tadornoides", group: "shelduck", status: "LC", len: "55–72",
    regions: "OC", habitat: "Large lakes, pastures and coasts of southern Australia.",
    marks: "Black head with a green sheen, white neck ring, cinnamon breast and dark body.",
    about: "Also called the Mountain Duck; it often grazes in paddocks.",
    colors: ["1E2A22", "1E1E1E", "C8843A", "3A3A36"],
  },
  {
    id: "paradise-shelduck", name: "Paradise Shelduck", sci: "Tadorna variegata", group: "shelduck", status: "LC", len: "63–71",
    regions: "OC", habitat: "Pastures, lakes and riverbeds across New Zealand.",
    marks: "Male is dark grey-black; the female has a bright white head and chestnut body, unusually more colourful.",
    about: "Pairs mate for life and loudly honk (males) and shriek (females) in duet.",
    colors: ["1E1E1E", "1E1E1E", "3A3A36", "3A3A36"],
  },
  {
    id: "radjah-shelduck", name: "Radjah Shelduck", sci: "Radjah radjah", group: "shelduck", status: "LC", len: "50–61",
    regions: "OC AS", habitat: "Mangroves and coastal swamps of northern Australia and New Guinea.",
    marks: "White head and body, chestnut-black back and breast band, pale pink bill.",
    about: "Also called the Burdekin Duck.",
    colors: ["F4F4F2", "E8B8B8", "5A3A2A", "F4F4F2"],
  },
  {
    id: "crested-shelduck", name: "Crested Shelduck", sci: "Tadorna cristata", group: "shelduck", status: "CR", len: "60–64",
    regions: "AS", habitat: "Formerly coasts and rivers of Korea, Japan and Russia's Far East.",
    marks: "Dark green crest, grey body, and pale face.",
    about: "Known from only a handful of specimens and sightings; not confirmed since 1964.",
    colors: ["1E3A30", "D9362F", "5A5A56", "8A8C88"],
  },
  {
    id: "blue-duck", name: "Blue Duck (Whio)", sci: "Hymenolaimus malacorhynchos", group: "shelduck", status: "EN", len: "53",
    regions: "OC", habitat: "Fast, clear mountain rivers of New Zealand.",
    marks: "Slate blue-grey with a chestnut-speckled breast, yellow eye and a pale pink bill with soft flaps at the tip.",
    about: "Featured on New Zealand's $10 note; the name 'whio' imitates the male's whistle.",
    colors: ["5E6E80", "F0D8D8", "6E6A62", "5E6E80"],
  },
  {
    id: "torrent-duck", name: "Torrent Duck", sci: "Merganetta armata", group: "shelduck", status: "LC", len: "43–46",
    regions: "SA", habitat: "Whitewater rapids of the Andes.",
    marks: "Striped black-and-white head and neck, red bill, streaked body and a stiff tail for bracing against rocks.",
    about: "Swims up raging waterfalls and has spurs on its wings for fighting.",
    colors: ["F4F4F2", "D9362F", "3A3A36", "5A5A56"],
  },
  {
    id: "flying-steamer-duck", name: "Flying Steamer Duck", sci: "Tachyeres patachonicus", group: "shelduck", status: "LC", len: "66–71",
    regions: "SA", habitat: "Lakes and coasts of Patagonia and Tierra del Fuego.",
    marks: "Big, grey, heavy-bodied duck with an orange-yellow bill. The only steamer duck that can fly.",
    about: "'Steaming' is how steamers flee: paddling along with their wings like a paddle steamer.",
    colors: ["8A8C90", "F0A030", "8A8C90", "7A7C80"],
  },
  {
    id: "fuegian-steamer-duck", name: "Fuegian Steamer Duck", sci: "Tachyeres pteneres", group: "shelduck", status: "LC", len: "74–84",
    regions: "SA", habitat: "Rocky coasts of southern Chile and Tierra del Fuego.",
    marks: "Huge, flightless and grey with an orange bill.",
    about: "Also called the Magellanic Steamer Duck; the largest steamer duck at up to 6 kg.",
    colors: ["8A8C90", "F0A030", "8A8C90", "7A7C80"],
  },
  {
    id: "falkland-steamer-duck", name: "Falkland Steamer Duck", sci: "Tachyeres brachypterus", group: "shelduck", status: "LC", len: "61–74",
    regions: "SA", habitat: "Coasts of the Falkland Islands.",
    marks: "Flightless, grey, with a pale grey head and orange bill.",
    about: "So aggressive that it has been seen killing other waterbirds that stray into its territory.",
    colors: ["B8BABC", "F0A030", "8A8C90", "7A7C80"],
  },
  {
    id: "white-headed-steamer-duck", name: "White-headed Steamer Duck", sci: "Tachyeres leucocephalus", group: "shelduck", status: "VU", len: "61–74",
    regions: "SA", habitat: "A short stretch of the Chubut coast in Argentina.",
    marks: "Flightless grey steamer duck; males have a white head and orange bill.",
    about: "Has one of the smallest ranges of any duck.",
    colors: ["F4F4F2", "F0A030", "8A8C90", "7A7C80"],
  },
  {
    id: "freckled-duck", name: "Freckled Duck", sci: "Stictonetta naevosa", group: "shelduck", status: "LC", len: "50–60",
    regions: "OC", habitat: "Dense, well-vegetated swamps of inland Australia.",
    marks: "Dark grey-brown, finely freckled with white; a peaked head and a red base to the bill in breeding males.",
    about: "An ancient lineage with no close relatives among living waterfowl.",
    colors: ["4A4640", "D84A3A", "5A5650", "5A5650"],
  },
  {
    id: "pink-eared-duck", name: "Pink-eared Duck", sci: "Malacorhynchus membranaceus", group: "shelduck", status: "LC", len: "36–45",
    regions: "OC", habitat: "Shallow, muddy inland wetlands of Australia.",
    marks: "Zebra-striped flanks, big square-tipped bill with soft flaps, a dark eye patch and a tiny pink ear spot.",
    about: "Groups spin in pairs, bill to tail, to concentrate plankton.",
    colors: ["E8E4DA", "4A4F58", "D8D4CC", "B8B4AC"],
  },
  {
    id: "marbled-duck", name: "Marbled Duck", sci: "Marmaronetta angustirostris", group: "shelduck", status: "VU", len: "39–42",
    regions: "EU AS AF", habitat: "Shallow, well-vegetated lakes in Spain, North Africa, the Middle East and Central Asia.",
    marks: "Pale sandy-brown with creamy spots, a dark eye patch and a slight shaggy crest.",
    about: "Its genus sits between the dabbling ducks and the pochards.",
    colors: ["C8B89C", "2A2A2A", "C8B89C", "B8A888"],
  },
  {
    id: "salvadoris-teal", name: "Salvadori's Teal", sci: "Salvadorina waigiuensis", group: "shelduck", status: "VU", len: "38–43",
    regions: "OC", habitat: "Fast mountain streams and lakes in New Guinea.",
    marks: "Dark brown head, barred brown-and-white body and a yellow bill.",
    about: "One of the least-known ducks, living high in New Guinea's mountains.",
    colors: ["4A3A2C", "E8C040", "8A7864", "8A7864"],
  },

  // ── Domestic breeds ───────────────────────────────────────────────
  {
    id: "pekin", name: "Pekin (White Pekin)", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "60–70",
    regions: "NA EU AS AF OC SA", habitat: "Farms, park ponds and backyards worldwide.",
    marks: "Big, all-white or creamy duck with a bright orange-yellow bill and orange legs.",
    about: "The classic farmyard white duck, domesticated from the Mallard in China.",
    colors: ["F7F4EC", "F2A030", "F7F4EC", "F7F4EC"],
    x: {
      weight: "3.5–4.5 kg", wingspan: "About 90 cm", lifespan: "8–12 years",
      voice: "Loud, typical Mallard-style quacks from females.",
      facts: [
        "Too heavy to fly more than a short hop.",
        "Most 'rubber duck'-coloured ducklings sold in spring are Pekins.",
      ],
    },
  },
  {
    id: "rouen", name: "Rouen", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "65–75",
    regions: "EU NA", habitat: "Farms, parks and backyards.",
    marks: "Looks like a supersized Mallard with a deep, boat-shaped body.",
    about: "A French breed kept mainly for show and meat.",
    colors: ["1F7A4D", "F2C230", "7B3F24", "B8BCC0"],
  },
  {
    id: "indian-runner", name: "Indian Runner", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "60–80 (standing)",
    regions: "AS EU NA OC", habitat: "Farms, gardens and orchards.",
    marks: "Stands bolt upright like a bowling pin and runs instead of waddling. Comes in white, fawn, black and other colours.",
    about: "Used for pest control in rice paddies and vineyards.",
    colors: ["C8A882", "8AA070", "E8DCC8", "C8A882"],
  },
  {
    id: "cayuga", name: "Cayuga", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "55–65",
    regions: "NA EU", habitat: "Farms and backyards.",
    marks: "All-black with a brilliant beetle-green sheen and a black bill.",
    about: "Its eggs can be grey or even black at the start of laying season.",
    colors: ["1A2A22", "1E1E1E", "1A2A22", "1A2A22"],
  },
  {
    id: "khaki-campbell", name: "Khaki Campbell", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "50–60",
    regions: "EU NA OC AS", habitat: "Farms and backyards.",
    marks: "Khaki-brown all over; drakes have a darker olive-bronze head and a greenish bill.",
    about: "One of the best egg-laying ducks, producing up to 300 eggs a year.",
    colors: ["5A5A3A", "6A7A4A", "A08A62", "A08A62"],
  },
  {
    id: "call-duck", name: "Call Duck", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "30–40",
    regions: "EU NA AS", habitat: "Show pens, gardens and small ponds.",
    marks: "Tiny, round and cute with a very short bill. Often white or Mallard-coloured.",
    about: "Originally bred as decoys to 'call' wild ducks into traps, so they're very loud.",
    colors: ["F7F4EC", "F2A030", "F7F4EC", "F7F4EC"],
  },
  {
    id: "swedish-blue", name: "Swedish Blue", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "55–65",
    regions: "EU NA", habitat: "Farms and backyards.",
    marks: "Slate-blue body with a white bib on the chest.",
    about: "Blue is a 'blending' colour: two blue parents produce blue, black and silver ducklings.",
    colors: ["4A5A6E", "3A4A5A", "F4F4F2", "5E6E82"],
  },
  {
    id: "crested-domestic", name: "Crested Duck (domestic)", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "55–65",
    regions: "EU NA AS", habitat: "Farms, parks and backyards.",
    marks: "A pom-pom of feathers on top of the head; usually white.",
    about: "The crest comes from a skull mutation, so breeders keep an eye on the birds' health.",
    colors: ["F7F4EC", "F2A030", "F7F4EC", "F7F4EC"],
  },
  {
    id: "buff-orpington", name: "Buff Orpington", sci: "Anas platyrhynchos domesticus", group: "domestic", status: "DOM", len: "55–65",
    regions: "EU NA OC", habitat: "Farms and backyards.",
    marks: "Warm buff to golden-fawn all over; drakes have a slightly darker brownish head.",
    about: "Bred in Orpington, Kent, in the 1890s as a dual-purpose egg and meat duck.",
    colors: ["B08A5A", "D8A040", "D8B888", "D8B888"],
  },
  {
    id: "muscovy-domestic", name: "Domestic Muscovy", sci: "Cairina moschata domestica", group: "domestic", status: "DOM", len: "65–85",
    regions: "NA SA EU AF AS OC", habitat: "Farms, town ponds and canals, especially in Florida and Texas.",
    marks: "Big, flat-bodied duck with bright red warty skin around the eyes and bill; plumage white, black or pied.",
    about: "Feral Muscovies roost in trees and happily eat flies, mosquitoes and even small rodents.",
    colors: ["F4F4F2", "E07A7A", "1E2A22", "F4F4F2"],
  },
];

export const SPECIES_BY_ID = Object.fromEntries(SPECIES.map((s) => [s.id, s]));
